services:
  - type: web
    name: redxbot302
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_NAME
        value: 🔥 REDXBOT302 🔥
      - key: PREFIX
        value: "."
